# Можно использовать https://editor-next.swagger.io/

openapi: 3.1.0
info:
  title: Card Delivery
  version: 1.0.0
servers:
  - url: https://card.swagger.io/api/v3

paths:
  /createOrder:
    post:
      summary: Add a new order
      description: Add a new order
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
        '205':
          description: Error operation (Invalid input)

  
  /getOrderStatusById/{id}:
    get:
      summary: Request to get order status
      description: Request to get order status
      operationId: getOrderStatusById
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          schema:
            type: string
            enum:
              - in_progress
              - canceled
              - rejected
              - completed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value


components:
  schemas:
    Order:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
          examples: [198772]
        userInfo:
          type: array
          items:
        cardInfo:
          type: array
          items:
        shipmentInfo:
          type: array
          items:


  securitySchemes:
    BasicAuth:
      type: http
      login: 
      password:
    BearerAuth:
      type: http
      scheme: bearer
