openapi: 3.1.0
info:
  title: Rick and Morty Navigator
  version: 1.0.0
servers:
  - url: localhost

paths:
  /CreateAdventure:
    post:
      summary: Add new adventure
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAdventure'
      responses:
        '200':
          description: Successful operation
        '306':
          description: Adventure is not found

  
  /whereAreRickAndMorty?/{id}:
    get:
      summary: Get current location
      parameters:
        - name: status
          in: path
          description: Filter by adventure status
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAdventure'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid status value



components:
  schemas:
    CreateAdventure:
      type: object
      properties:
        destination:
          type: string
          examples: [Галактика NGX 1330]
        destinatioLocation:
          type: object
          properties:
            lng:
              type: string
              examples: ["0.00"]
            lat:
              type: string
              examples: ["0.00"]
    
    
    
    
    GetAdventure:
      type: object
      properties:
        id:
          type: string
          examples: [a09e59b9-5dac-41e2-a0dc-362c94da5c94]
        destination:
          type: string
          examples: [Галактика NGX 1330]
        status:
          type: string
          examples: [В пути]
        currentLocation:
          type: object
          properties:
            lng:
              type: string
              examples: ["0.00"]
            lat:
              type: string
              examples: ["0.00"]
